### PR TITLE
Fix taking ownership of scene owned objects on leave

### LINKED ISSUE #2370: Pinned videos reset play position if user who last interacted with video re-enters room
If the last person who interacted with a pinned video re-enters a room, the video progress will reset back to the start for everyone. This only happens with pinned videos, but it doesn't matter if it's the owner or someone else who last interacted with it. 

1. Enter room with two tabs.
2. Spawn a video on one tab, and pin it. 
3. Interact with the video (e.g. advance ahead 30 seconds) on one of the tabs.
4. Whichever tab was used in step 3, refresh it.
5. Observe that in the other tab, the video state resets back to the beginning.

### PR DESCRIPTION
**Pull request by netpro2k**
"persistent" objects are supposed to have their ownership transferred when the creator of the object leaves the room, rather than being removed.

"scene owned" objects do not have a "creator", so the logic for taking ownership over them when people leave does not trigger. This was noticed when testing media frames but is likely the source of several other bugs in Hubs like scene owned videos restarting randomly when people join the room. (Happens because the person who owned the video left, leaving no owner).

The existing code could also lead to persistent objects being removed if anyone failed the `takeOwnership` call, which could happen if the object recently changed ownership before the "creator" left. This could explain some of the pinned objects disappearing we have seen.

The handling for scene owned objects still feels pretty peace-meal and special logic still exists for videos in Hubs to take ownership on scene load. This should get moved into NAF such that scene owned objects are only a transitory state and once running all objects should always maintain an owner. Will leave that for another PR though.

fixes https://github.com/mozilla/hubs/issues/2370

### CODE REVIEW

File: src/NetworkEntities.js [hunk 1]
```diff
@@ -156,15 +156,13 @@ class NetworkEntities {
...
-        if (!persists) {
-          var entity = this.removeEntity(id);
-          entityList.push(entity);
+      var entityOwner = NAF.utils.getNetworkOwner(this.entities[id]);
+      if (entityCreator === clientId || (!entityCreator && entityOwner === clientId)) {
+        if (this.entities[id].getAttribute("networked").persistent) {
+          // everyone will attempt to take ownership, someone will win, it does not particularly matter who
+          NAF.utils.takeOwnership(this.entities[id]);
+        } else {
+          entityList.push(this.removeEntity(id));
```
Comment (johnshaughnessy) [inline src/NetworkEntities.js]: A few suggestions on naming, take 'em or leave 'em: 
- add `var entity = this.entities[id];`
- drop `entity` from `entityCreator/entityOwner` 
- rename `entityList` -> `removedEntities`

File: src/NetworkEntities.js [hunk 2]
```diff
@@ -156,15 +156,13 @@ class NetworkEntities {
...
-        const component = this.entities[id].getAttribute('networked');
-        if (component && component.persistent) {
-          persists = NAF.utils.isMine(this.entities[id]) || NAF.utils.takeOwnership(this.entities[id]);
-        }
-        if (!persists) {
-          var entity = this.removeEntity(id);
-          entityList.push(entity);
+      var entityOwner = NAF.utils.getNetworkOwner(this.entities[id]);
+      if (entityCreator === clientId || (!entityCreator && entityOwner === clientId)) {
+        if (this.entities[id].getAttribute("networked").persistent) {
```
Comment (johnshaughnessy) [inline src/NetworkEntities.js]: The previous version has a guard against `this.entities[id].getAttribute("networked")` being `falsey`
>  `if (component && component.persistent) {`

Not sure if the guard is necessary but pointing it out in case it was an unintentional change.

**Review by brianpeiris — APPROVED** [review]
Good points from John. Looks good to me otherwise. Nice find!
I think the CI build was broken long before this change, but it would be nice if you could take a look at fixing it while you're here.

File: src/NetworkEntities.js (hunk 2 above)
Comment (netpro2k) [reply src/NetworkEntities.js]: Don't think its needed, but did not intend to make that change here.. Will leave in for now even though it seems overly defensive.

**Review by johnshaughnessy — APPROVED** [review]
